name: UI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: browser-actions/setup-chrome@v1

      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt

      - name: Run tests (headless)
        run: |
          HEADLESS=1 pytest -q --junitxml=pytest-results.xml

      - name: Upload JUnit results
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: pytest-results.xml
